# Generated by Django 4.1.7 on 2023-04-03 04:53

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import todos.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (0, "Urgent"),
                            (1, "High"),
                            (2, "Medium"),
                            (3, "Low"),
                            (4, "Trivial"),
                        ],
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(max_length=2000)),
                (
                    "project",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "share",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=2083),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "references",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=2083),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "related",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(
                            validators=[todos.models.validate_related_task_id]
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "estimate",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\d+(w|d|h|m)$")
                        ],
                    ),
                ),
                (
                    "note_array",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Task",),
        migrations.DeleteModel(name="TaskSpecial",),
    ]
